### ISSUE TITLE
How do you configure this component to work with HA ?

### ISSUE THREAD

**Issue by DzzD** [ms32035/home-assistant-ubibot#1]
Hi there,

You have  made a nice component here, I have forked to try to modify it to match my own ubitot sensor, but anyway I am pretty noob with HA could you esplain how to install and configure it plz ? a README.md would be really great add to this repository.

For now I have just put it on "custom_components" folder and it appear on the integration list on HA interface but it say that it requiere manual installation and I don know how to proceed...

**Comment by DzzD** [comment]
> Hi there,
> 
> You have made a nice component here, I have forked to try to modify it to match my own ubitot sensor, but anyway I am pretty noob with HA could you esplain how to install and configure it plz ? a README.md would be really great add to this repository.
> 
> For now I have just put it on "custom_components" folder and it appear on the integration list on HA interface but it say that it requiere manual installation and I don know how to proceed...

Also I have to said that I have traced the request send (using my computer as a WIFI access point+WireShark) and it look easy to understand as it is not HTTPS but simple HTTP, If I spoof the DNS and redirect to my own HTTP server I should be able to make a server that imitate ubibot server that did not require Ubibot cloud or account anymore.

Here is what it how exchanges look like (note that it say it is using an ESP32...) :

Sent by the UbiBot sennsor : 

```
POST /update.json?execute=true&metadata=true&api_key=eeeeeeerre99191bae9e02b5a93f202rrrr9df867970e&firmware=ws1a_v2.1.8&ssid_base64=UEMtRFpaRC1XUw== HTTP/1.1
User-Agent: ESP32 HTTP Client/1.0
Host: api.ubibot.io
Content-Type: application/json
Content-Length: 512

{"feeds":[{"created_at":"2022-11-26T20:25:19Z","field5":"-52.0000"},{"created_at":"2022-11-26T20:28:21Z","wifi":"f2:b6:1e:31:40:ca,-20;b0:a7:b9:b8:6e:dd,-55;32:cd:a7:fd:fb:17,-66;bc:2e:f6:fa:92:35,-80;,0"}],"cali":{"f1_a":1,"f1_b":-0.5,"f2_a":1,"f2_b":0,"f3_a":1,"f3_b":0,"f4_a":1,"f4_b":0,"f5_a":1,"f5_b":0,"f6_a":1,"f6_b":0,"f7_a":1,"f7_b":0,"f8_a":1,"f8_b":0.5,"f9_a":1,"f9_b":0,"f10_a":1,"f10_b":0},"status":"mac=xxxxxxxx,usb=1,ota_status=0,ota_errcode=0,ota_sec=0","ssid_base64":"UEMtRFpaRC1XUw=="}
```

Server Response : 

```
HTTP/1.1 200 OK
Server: nginx/1.14.2
Date: Sat, 26 Nov 2022 20:28:35 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Cache-Control: 
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS

{"result":"success","server_time":"202 etc... etc...}
```

**Comment by ms32035** [comment]
I updated the readme
